// frontend/src/app/wish/page.tsx
export default function WishPost() {
  return (
    <div className="bg-gradient-to-b from-yellow-50 to-yellow-100 w-screen h-screen flex flex-col items-center justify-between py-12">
      <header className="bg-white shadow-lg rounded-lg px-8 py-4 text-4xl font-bold text-yellow-600">
        Techeer Tree
      </header>
      <div className="w-full max-w-md bg-white shadow-md rounded-lg p-8 my-auto">
        <h2 className="text-2xl font-bold text-center text-yellow-600 mb-6">
          소원 열매 달기
        </h2>
        <form className="flex flex-col gap-4">
          <div>
            <label className="block text-gray-700">제목</label>
            <input
              type="text"
              className="w-full p-2 border border-gray-300 rounded mt-1"
            />
          </div>
          <div>
            <label className="block text-gray-700">내용</label>
            <textarea className="w-full p-2 border border-gray-300 rounded mt-1" />
          </div>
          <div>
            <label className="block text-gray-700">카테고리</label>
            <select className="w-full p-2 border border-gray-300 rounded mt-1">
              <option value="">카테고리 선택</option>
              <option value="진로">진로</option>
              <option value="건강">건강</option>
              <option value="인간 관계">인간 관계</option>
              <option value="돈">돈</option>
              <option value="목표">목표</option>
              <option value="학업/성적">학업/성적</option>
              <option value="기타">기타</option>
            </select>
          </div>
          <button
            type="submit"
            className="bg-yellow-500 text-white px-6 py-2 rounded-lg shadow-md hover:bg-yellow-600 transition-all duration-200"
          >
            소원 등록
          </button>
        </form>
      </div>
    </div>
  )
}

// src/routes/wish/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let permissions: string;
	let selectedCategory: string = '';
	let subject = '';
	let category = '';
	let content = '';

	onMount(() => {
		permissions = localStorage.getItem('permissions') || '';
	});
</script>

<div class="page">
	{#if permissions === 'admin'}
		<div class="warning">권한 없음</div>
		<div class="warning-content">Admin은 소원 열매를 달 수 없습니다. 😢</div>
	{:else}
		<div class="post">
			<div class="title">소원 제목</div>
			<input class="subject-input" />
		</div>

		<div class="post">
			<div class="title">소원 카테고리</div>
			<select bind:value={selectedCategory} class="category-select">
				<option value="" disabled selected>카테고리를 선택하세요</option>
				<option value="진로">진로</option>
				<option value="건강">건강</option>
				<option value="인간 관계">인간 관계</option>
				<option value="돈">돈</option>
				<option value="목표">목표</option>
				<option value="학업/성적">학업/성적</option>
				<option value="기타">기타</option>
			</select>
		</div>

		<div class="post">
			<div class="title">소원 내용</div>
			<input class="content-input" />
		</div>
		<div class="post">
			<div class="title" />
			<button class="submit">소원 열매 달기</button>
		</div>
	{/if}
</div>

<style lang="scss">
	// 변수 선언
	$font-size-large: 2rem;
	$font-size-medium: 1.25rem;
	$input-height: 3rem;
	$border-color: #aaa;
	$focus-border-color: #aaa;
	$input-width: 50%;
	$primary-bg-color: $primary-color;
	$hover-bg-color: darken($primary-color, 3%);

	// 믹스인 정의
	@mixin input-style {
		width: $input-width;
		height: $input-height;
		margin-left: 1rem;
		border: 2px solid $border-color;
		font-size: $font-size-medium;
		padding: 0.25rem;

		&:focus {
			outline: none;
			border: 2px solid $focus-border-color;
		}
	}

	.page {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		min-height: calc(100vh - $header-height);

		.warning {
			font-size: $font-size-large;
			font-weight: bold;
			color: $primary-color;
		}

		.warning-content {
			font-size: $font-size-medium;
		}

		.post {
			display: flex;
			flex-direction: row;
			justify-content: center;
			align-items: center;
			width: 100%;
			height: 100%;
			font-size: $font-size-medium;
			margin-bottom: 1rem;

			.title {
				width: 10%;
				font-weight: bold;
				text-align: right;
			}

			.subject-input,
			.category-select,
			.content-input {
				@include input-style;
			}

			.content-input {
				height: calc(4 * $input-height);
			}
		}

		.submit {
			@include input-style;
			background-color: $primary-bg-color;
			color: white;
			cursor: pointer;

			&:hover {
				background-color: $hover-bg-color;
			}
		}
	}
</style>
